---
- name: Add the user {{ user }}
  remote_user: pi
  become: yes
  user:
    name: "{{ user }}"
    groups: adm,sudo,wheel,audio,video,users
    shell: /bin/bash
    generate_ssh_key: yes

- name: Set authorized key taken from file
  remote_user: pi
  become: yes
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '/home/{{ user }}/.ssh/id_rsa.pub') }}"

- name: Set {{ user }} as the autologin user
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^autologin-user='
    line: "autologin-user={{ user }}"

- name: Install software
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - vim-gtk3
      - irssi
      - tmux

- name: Clone dotfiles
  git:
    repo: https://github.com/atonal/dotfiles.git
    dest: "/home/{{ user }}/dotfiles"

- name: Install dotfiles
  command: ./install.sh
  args:
    chdir: "/home/{{ user }}/dotfiles"
