---
- name: Install software
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - vim-gtk3
      - irssi
      - tmux

- name: Clone dotfiles
  git:
    repo: https://github.com/atonal/dotfiles.git
    dest: "/home/{{ user }}/dotfiles"

- name: Install dotfiles
  command: ./install.sh
  args:
    chdir: "/home/{{ user }}/dotfiles"
