---
- name: Configure groups for {{ user }}
  become: yes
  user:
    name: "{{ user }}"
    groups: adm,sudo,wheel,audio,video,users
    shell: /bin/bash
    generate_ssh_key: yes

- name: Install software
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - vim-gtk3
      - irssi
      - tmux

- name: Check if home is git repo
  git:
    repo: https://github.com/atonal/home.git
    dest: "/home/{{ user }}"
    clone: no
    update: no
  register: home_is_repo

- name: Init repo
  shell: |
    git init
    git remote add origin https://github.com/atonal/home.git
    git fetch
    git checkout -f master
    ./home-install.sh
  args:
    chdir: "/home/{{ user }}"
  when: home_is_repo.before is none
