---
- name: Add wheel group
  remote_user: pi
  become: yes
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  remote_user: pi
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
