---
- name: Add raspotify apt key
  become: yes
  apt_key:
    url: https://dtcooper.github.io/raspotify/key.asc

- name: Add raspotify repository
  become: yes
  apt_repository:
    repo: deb https://dtcooper.github.io/raspotify raspotify main

- name: Install raspotify
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - curl
      - apt-transport-https
      - raspotify

- name: Configure raspotify
  become: yes
  lineinfile:
    path: /etc/default/raspotify
    regexp: 'BITRATE='
    line: 'BITRATE="320"'
  notify:
    - restart raspotify

- name: check if asound file exists
  stat:
    path: /var/lib/alsa/asound.state
  register: asound_state

- name: Copy asound.state to host
  become: yes
  copy:
    src: asound.state
    dest: /var/lib/alsa/asound.state
    owner: root
    group: root
    mode: '0644'
  when: not asound_state.stat.exists
  notify:
    - restore alsa

- name: Force audio output to jack
  # same as running: amixer cset numid=3 1
  # need to hook to?: name 'PCM Playback Route'
  become: yes
  replace:
    path: /var/lib/alsa/asound.state
    after: 'control.3'
    before: 'control.4'
    regexp: '(\s*value)\s*\d.*'
    replace: '\1 1'
  notify:
    - restore alsa
