---
- hosts: vattu
  gather_facts: no
  pre_tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      remote_user: "{{ user }}"
      wait_for_connection:
    - name: Wait 300 seconds for target ssh to become reachable/usable
      remote_user: "{{ user }}"
      wait_for:
        port: 22
  roles:
    - user
    - spotify
    - remote
    - kubernetes
